services:
  - type: web
    name: appgacha-backend
    runtime: python-3.11
    plan: free
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'gunicorn --workers 4 --worker-class sync --timeout 120 --bind 0.0.0.0:$PORT app_backend_clean:app'
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: '*'
      - key: JWT_SECRET
        value: your-secret-key-change-me
      - key: MONGODB_URI
        value: mongodb+srv://AppMobile04:duypro0478@cluster0.tvfipwr.mongodb.net/appgacha?retryWrites=true&w=majority&ssl=true

databases:
  - name: appgacha-mongodb
    databaseName: appgacha
    plan: free
